### ISSUE TITLE
Fix alignment of headings

### ISSUE THREAD

**Issue by fangohr** [joommf/joommf.github.io#1]
Example from http://joommf.github.io/faqs.html :

<img width="409" alt="screen shot 2016-10-17 at 18 42 14" src="https://cloud.githubusercontent.com/assets/4489119/19448517/12126884-949a-11e6-9ba6-79185021b1b4.png">

Can we align the different headings (to make it look better)?

**Comment by davidcortesortuno** [comment]
Sure, I'll take a look into it

**Comment by davidcortesortuno** [comment]
I fixed the alignment, I also added the date on the News section

**Comment by fangohr** [comment]
+1
